### ISSUE TITLE
README customization code does not work

### ISSUE THREAD

**Issue by macklinu** [rubymonolith/superform#20]
Hello, I am trying to get started with Superform and Phlex, but the example in the [Customization](https://github.com/rubymonolith/superform?tab=readme-ov-file#customization) section is not working with superform v0.4.5. I'd love to figure out what is needed here, because being able to override different form component as mentioned in the superform README styles for usage with Tailwind makes _much_ more sense to me conceptually than messing around with Rails FormBuilder.

Steps to reproduce:
- `rails new superform_example`
- `cd superform_example`
- `rails g scaffold User name email`
- `rails db migrate`
- `bundle add superform --version 0.4.5`
- `rails g superform:install`
- Update `app/views/forms/application_form.rb`
```rb
# ./app/views/forms/application_form.rb
class ApplicationForm < ApplicationForm
  class MyInputComponent < ApplicationComponent
    def template(&)
      div class: "form-field" do
        input(**attributes)
        if field.errors?
          p(class: "form-field-error") { field.errors.to_sentence }
        end
      end
    end
  end

  class Field < Field
    def input(**attributes)
      MyInputComponent.new(self, attributes: attributes)
    end
  end

  def labeled(component)
    div class: "form-row" do
      render component.field.label
      render component
    end
  end

  def submit(text)
    button(type: :submit) { text }
  end
end
```
- Create `app/views/users/form.rb`
```rb
# ./app/views/users/form.rb
class Users::Form < ApplicationForm
  def template(&)
    labeled field(:name).input
    labeled field(:email).input(type: :email)

    submit "Sign up"
  end
end
```
- Update `app/views/users/new.html.erb` to render the form:
```erb
<h1>New user</h1>

<%= render Users::Form.new @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

```
- `rails s`
- Visit http://localhost:3000/users/new

**Expected**: `Users::Form` renders
**Actual**: Rendering error
```
ActionView::Template::Error (wrong number of arguments (given 2, expected 0)):
    1: <h1>New user</h1>
    2: 
    3: <%= render Users::Form.new @user %>
    4: 
    5: <br>
    6: 
  
app/views/forms/application_form.rb:15:in `input'
app/views/users/form.rb:3:in `template'
app/views/users/new.html.erb:3
```
![image](https://github.com/rubymonolith/superform/assets/2344137/e884582b-9332-4baa-ba1d-d6743f5ce1ea)

**Comment by macklinu** [comment]
This is what I've been able to get working. The only thing I'm not sure about is where `errors?` and `errors` come from.

```rb
class ApplicationForm < Superform::Rails::Form
  class MyInputComponent < Superform::Rails::Components::InputComponent
    def template(&)
      div class: "form-field" do
        input(**attributes)
        # if field.errors?
        #   p(class: "form-field-error") { field.errors.to_sentence }
        # end
      end
    end
  end

  class Field < Superform::Rails::Form::Field
    def input(**attributes)
      MyInputComponent.new(self, attributes:)
    end
  end

  def labeled(component)
    div class: "form-row" do
      render component.field.label
      render component
    end
  end

  def submit(text)
    button(type: :submit) { text }
  end
end
```

If I uncomment the line with `field.errors?`, I get an `undefined method errors?` error.
